spring:
  application:
    name: mcp-nacos3-client
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # or ASYNC for reactive applications

    alibaba:
      mcp:
        nacos:
          client:
            enabled: true
            streamable:
              connections:
                server1:
                  service-name: webflux-mcp-server
                  version: 1.0.0
#                server2:
#                  service-name: webflux-mcp-server-yingzi
#                  version: 1.0.0
            configs:
              server1:
                namespace: 4ad3108b-4d44-43d0-9634-3c1ac4850c8c
                server-addr: 127.0.0.1:8848
                username: nacos
                password: nacos
#              server2:
#                namespace: 8237f998-2f01-4cf8-bfc1-64012d09cce2
#                server-addr: 127.0.0.1:8848
#                username: nacos
#                password: nacos
