server:
  port: 21000

spring:
  main:
    banner-mode: off
  application:
    name: mcp-nacos3-registry-server
  ai:
    mcp:
      server:
        name: webflux-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        protocol: STREAMABLE # STREAMABLE,STATELESS
        streamable-http:
          mcp-endpoint: /mcp
          #          keep-alive-interval: 30s
          disallow-delete: false
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    alibaba:
      mcp:
        nacos:
          namespace: 4ad3108b-4d44-43d0-9634-3c1ac4850c8c
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          register:
            enabled: true
            service-group: mcp-server
            service-name: webflux-mcp-server
      toolcalling:
        weather:
          enabled: true
          api-key: ${WEATHER_API_KEY}