server:
  port: 19101

spring:
  application:
    name: mcp-security-client
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 600s
        type: ASYNC  # or ASYNC for reactive applications
        sse:
          connections:
            server1:
              url: http://localhost:19000 # 本地

  security:
    oauth2:
      client:
        provider:
          authserver:
            issuer-uri: http://localhost:9000
        registration:
            authserver:
                client-id: mcp-security-client
                client-secret: default-secret
                authorization-grant-type: authorization_code
                provider: authserver